WITH RECURSIVE n(x) AS (
  SELECT 2
  UNION ALL
  SELECT x + 1 FROM n WHERE x < 1000
),
d(y) AS (
  SELECT 2
  UNION ALL
  SELECT y + 1 FROM d WHERE y < 1000
)
SELECT GROUP_CONCAT(x ORDER BY x SEPARATOR '&')
FROM n
WHERE NOT EXISTS (
  SELECT 1
  FROM d
  WHERE y <= FLOOR(SQRT(x))
    AND x % y = 0
);
